Portal/talabarteria/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :indicators
  devise_for :users
  get 'welcome/index'
  get 'creatives/index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'creatives#index'
end

Portal/talabarteria/app/models/indicator.rb
class Indicator < ApplicationRecord

	#Validaciones
	validates :beneficiary, length: {minimum: 4, message: "El nombre del beneficiario debe ser minimo de 4 carácteres"}
	validates :impact, length: {minimum: 4, message: "El impacto debe ser minimo de 4 carácteres"}
	validates :description, length: {minimum: 8, message: "La descripción debe ser minimo de 8 carácteres"}
	validates :image, presence:  {message: "Debe seleccionar una imagen"}
	#Archivo adjunto para la imagen del indicador
	has_attached_file :image, styles: { medium: "1200x720", thumb: "800x600", mini: "400x200"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

Portal/talabarteria/app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create 
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:beneficiary, :impact, :description, :image)
    end
end

Portal/talabarteria/app/helpers/indicators_helper.rb
module IndicatorsHelper
end

Portal/talabarteria/app/views/indicators/_form.html.erb
<div style="width: 80%;margin: 0 auto;">
<%= form_for(indicator) do |f| %>
  <% if indicator.errors.any? %>
    <div class="field">
      <h2>Error</h2>

      <ul>
      <% indicator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :beneficiary, placeholder: "Beneficiario", class: "forma" %>
  </div>

  <div class="field">
    <%= f.text_field :impact, placeholder: "Impacto" , class: "forma"%>
  </div>

  <div class="field">
    <%= f.text_area :description, placeholder: "Escriba aqui una descripción", style:"height:180px", class: "forma" %>
  </div>

  <div class="field">
      <table>
        <tr>
          <td>
            <%= f.label 'Imagen: ', style: "padding-right: 15px;" %>
          </td>
          <td>
            <%= f.file_field :image %>
          </td>
        </tr>
      </table>
    </div>  

  <div class="actions center-xs">
    <%= f.submit %>
  </div>
<% end %>
</div>

Portal/talabarteria/app/views/indicators/edit.html.erb
<div class="row">
	<h1>Edición del Indicador</h1>
</div>
<div class="row">
	<%= render 'form', indicator: @indicator %>
</div>
<div class="row">
	<div class="field center-xs">
		<%= link_to 'Atras', root_path, class: "btn btn-primary btn-xl page-scroll" %>
	</div>
</div>

Portal/talabarteria/app/views/indicators/index.html.erb
<div class="row titulo">
  <h1>Indicadores</h1>
</div>
<div class="row large-padding">
  <% if user_signed_in? %>
    <%= link_to 'Nuevo Indicador', new_indicator_path %>
  <%end%>
</div>
<div class="row">
  <% @indicators.each do |indicator| %>
  <div class="cuadro col-sm-12" style="width: 80%;margin: 0 auto;"">
    <div class="field center-xs">
      <%= image_tag indicator.image.url(:thumb) %>
    </div>
    <div class="field center-xs">
       <%= indicator.description %>
    </div>
    <div class="field center-xs">
        <div class="btn be-red white">
          <%= link_to 'Ver', indicator %>
        </div>
        <% if user_signed_in? %>
          <div class="btn be-red">
             <%= link_to 'Eliminar', indicator, method: :delete, data: { confirm: '¿Estás Seguro?' } %>
          </div>
        <% end %>
    </div>
  </div>
  <% end %>
</div>

        

Portal/talabarteria/app/views/indicators/new.html.erb
<div class="row">
	<h1>Nuevo Indicador</h1>
</div>
<div class="row">
	<%= render 'form', indicator: @indicator %>
</div>
<div class=" row">
	<div class="field center-xs">
		<%= link_to 'Atras', root_path, class: "btn btn-primary btn-xl page-scroll" %>
	</div>
</div>

Portal/talabarteria/app/views/indicators/show.html.erb
<div class="row">
	<p id="notice"><%= notice %></p>
</div>
<div class="row">
	<div class="field center-xs">
		<p>
		  <strong>Beneficiario:</strong>
		  <%= @indicator.beneficiary %>
		</p>
	</div>
</div>
<div class="row">
	<div class="field center-xs">
		<p>
		  <strong>Impacto:</strong>
		  <%= @indicator.impact %>
		</p>
	</div>
</div>
<div class="row">
	<div class="field center-xs">
		<p>
	  <strong>Descripción:</strong>
	  <%= @indicator.description %>
	</p>
	</div>
</div>
<div class="row">
  <div class="field center-xs">
    <%= image_tag @indicator.image.url(:mini) %>
  </div>
</div> 
<div class="row">
  <div class="field center-xs">
  <% if user_signed_in? %>
	<%= link_to 'Editar', edit_indicator_path(@indicator), class: "btn btn-primary btn-xl page-scroll" %> |
	<% end %>
	<%= link_to 'Atras', root_path, class: "btn btn-primary btn-xl page-scroll" %>
  </div>
 </div>