Portal/talabarteria/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :indicators
  devise_for :users
  get 'welcome/index'
  get 'creatives/index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'creatives#index'
end

Portal/talabarteria/app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  	@products = Product.all
  	@indicators = Indicator.all
  end
end

Portal/talabarteria/app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Quiénes Somos...</h2>
                <hr class="light">
                <p class="text-faded">La Talabartería Montenegro fue creada en el año 1985 por su actual propietario José Hugo Ramírez Vélez, oriundo de esta región, actualmente es la única  talabartería que existe en el municipio de Montenegro, que en el transcurso de los años su reconocimiento se fue dispersando en la región, haciéndose conocer por su buena calidad de servicio!</p>
                <a href="#indicators" class="btn btn-default btn-xl">Indicadores!</a>
            </div>
        </div>
    </div>
</section>

Portal/talabarteria/app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Download at Start Bootstrap!</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
        </div>
    </div>
</aside>

Portal/talabarteria/app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Contáctenos!</h2>
                <hr class="primary">
                <p>Danos una llamada o envianos un correo electrónico y nos pondremos en contacto con usted tan pronto sea posible!</p>
            </div>

            <div class="col-lg-12 text-center">
                
                <p>
                    Visítanos<br>
                    Carrera 4 # 21 - 20 -<br>
                    Montenegro, Quindío <br><br>
                    Barrio la pista carrera <br>
                    4 # 21 - 22 -<br>
                    Montenegro, Quindío 
                </p>
            </div>

            <div class="col-lg-12 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>Llamános<br>
                    311 324 5363</p>
            </div>
            <div class="col-lg-12 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p>Escribenos <br><a href="mailto:your-email@your-domain.com">hugoramirezvelez@gmail.com</a></p>
            </div>
            <div class="col-lg-12 text-center">
                <% if user_signed_in? %>
                    <%= link_to "MENSAJES", messages_path, class: "btn btn-primary btn-xl page-scroll" %>
                <%else%>
                  <%= link_to "ENVIAR MENSAJE", new_message_path, class: "btn btn-primary btn-xl page-scroll" %>
                <%end%>
            </div>  
        </div>
    </div>
</section>

Portal/talabarteria/app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Talabartería Montenegro</h1>
            <hr>
            <p>Tenemos lo que usted necesita!</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Mas Información</a>
        </div>
    </div>
</header>

Portal/talabarteria/app/views/creatives/_indicators.html.erb
<section id="indicators">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Indicadores de Responsabilidad</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>
                       Los Indicadores de Responsabilidad, son una herramienta de aprendizaje y evaluación de la gestión de la Talabartería en lo que se refiere a la incorporación de prácticas de responsabilidad social empresarial, a la planificación de estrategias y el monitoreo del desempeño general de la empresa. Se trata de un instrumento de autoevaluación y aprendizaje de uso esencialmente interno. 
                    </p>
                </div>
            </div>
    </div>
    <% if user_signed_in? %>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <%= link_to 'Nuevo Indicador', new_indicator_path, class: "btn btn-primary btn-xl page-scroll" %>
                </div>
            </div>
        </div>
    <%end%>
    <% @indicators.each do |indicator| %>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    
                    <h3><%= indicator.beneficiary %></h3>
                        <%= image_tag indicator.image.url(:mini) %>
                    <p class="text-muted">
                        <%= indicator.description %>
                    </p>
                      <%= link_to 'Ver', indicator, class: "btn btn-primary btn-xl page-scroll" %>
                    <% if user_signed_in? %>
                         <%= link_to 'Eliminar', indicator, method: :delete, class: "btn btn-primary btn-xl page-scroll",data: { confirm: '¿Estás Seguro?' } %>
                    <% end %> 
                </div>
            </div>
        </div>
    <% end %>  
</section>

Portal/talabarteria/app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Talabartería", root_path, class: "navbar-brand page-scroll" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">Acerca de</a>
                </li>
                <li>
                    <a class="page-scroll" href="#indicators">Indicadores</a>
                </li>
                <li>
                    <a class="page-scroll" href="#products">Productos</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contáctenos</a>
                </li>
                
                <% if user_signed_in? %>
                    
                <li>
                    <%= link_to "CERRAR SESIÓN", destroy_user_session_path , method: :delete, class: "page-scroll" %>
                      
                </li>

                <%else%>
                
                <li>
                    <%= link_to "INICIAR SESIÓN", new_user_session_path, class: "page-scroll" %>
                </li>
                <%end%>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

Portal/talabarteria/app/views/creatives/_products.html.erb
<section class="no-padding" id="products">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Productos</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                 <% if user_signed_in? %>
                    <%= link_to 'Nuevo Producto', new_product_path, class: "btn btn-primary btn-xl page-scroll" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container-fluid">

            <% @products.each do |product| %>

            <div class="col-lg-12 ", style="margin-top: 10px;margin-bottom: : 10px; ">
                <a href="#products" class="portfolio-box">
                    <%= image_tag product.cover.url(:mini), class: "img-responsive", style: "margin: 0 auto;", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                <%= product.name %>
                            </div>
                        </div>
                    </div>
                </a>
                <div class="row">
                    <div class="col-lg-12 text-center", style="margin-top: 10px;">
                        <%= link_to 'Ver', product , class: "btn btn-primary btn-xl page-scroll"%>
                        <% if user_signed_in? %>
                            <%= link_to 'Eliminar', product, method: :delete, class: "btn btn-primary btn-xl page-scroll",data: { confirm: '¿Estás Seguro?' } %>
                        <% end %> 
                     </div>
                </div>
            </div> 

            <% end %>
            
        </div>
    </div>
</section>

Portal/talabarteria/app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'indicators' %>
<%= render 'products' %>
<%= render 'contact' %>