Portal/talabarteria/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :indicators
  devise_for :users
  get 'welcome/index'
  get 'creatives/index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'creatives#index'
end

Portal/talabarteria/app/views/partials/_footer.html.erb
            <div class="col-sm-4">
                <div class="icono">
                    <i class="material-icons iconos2">room</i>
                </div>
                <div class="texto">
                    Visítanos<br>
                    Carrera 4 # 21 - 20 -<br>
                    Montenegro, Quindío <br><br>
                    Barrio la pista carrera <br>
                    4 # 21 - 22 -<br>
                    Montenegro, Quindío 
                </div>          
            </div>
            <div class="col-sm-4">
                <div class="icono">
                    <i class="material-icons iconos2">phone</i>
                </div>
                <div class="texto">
                    Llamános<br>
                    311 324 5363 <br>
                </div>  
            </div>
            <div class="col-sm-4">
                <div class="icono">
                    <i class="material-icons iconos2">email</i>
                </div>
                <div class="texto">
                    Contáctanos<br>
                    hugoramirezvelez@gmail.com
                </div>
            </div>
       

Portal/talabarteria/app/views/partials/_navigation.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li class="col-md">
                        <a class="page-scroll fuente-negra" href="#">
                            <%= link_to "INICIO", root_path %>
                        </a>
                    </li>
                    <li class="col-md">
                        <a class="page-scroll" href="#">
                            <%= link_to "PRODUCTOS", products_path %>
                        </a>
                    </li>
                    <li class="col-md">
                        <a class="page-scroll" href="#about">
                            <%= link_to "INDICADORES", indicators_path %>
                        </a>
                    </li>
                    <li class="col-md">
                        <a class="page-scroll" href="#">
                            <% if user_signed_in? %>
                            <%= link_to "MENSAJES", messages_path %>
                            <%else%>
                            <%= link_to "CONTÁCTENOS", new_message_path %>
                            <%end%>
                        </a>
                    </li>
                    
                    <% if user_signed_in? %>
                    
                    <li class="col-md">
                        <a class="page-scroll" href="#">
                            <%= link_to "CERRAR SESIÓN", destroy_user_session_path , method: :delete %>
                      </a>
                    </li>

                    <%else%>
                    <li class="col-md">
                        <a class="page-scroll" href="#">
                            <%= link_to "INICIAR SESIÓN", new_user_session_path,styles: "color: #000000" %>
                            </a>
                    </li>
                    <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    
</header>